name: CI
on:
  # Only trigger this workflow for the 5.x branch
  push:
    branches:
      - 5.x
    tags:
      - v*
  pull_request:
    branches:
      - 5.x
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.libvips-version == 'master' }}
    strategy:
      fail-fast: true
      matrix:
        include:
          # TODO(kleisauke): Enable once tiffsave_target/magickload_source is supported
          # - os: ubuntu-20.04
          #   libvips-version: master
          - os: ubuntu-20.04
            libvips-version: 8.12.2
            coverage: true
    steps:
      - uses: actions/checkout@v3
      - name: Cache libvips
        if: matrix.libvips-version != 'master'
        id: cache-libvips
        uses: actions/cache@v3
        with:
          path: ~/vips
          key: ${{ matrix.libvips-version }}
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
        run: |
          # for Test::Nginx
          curl -sSL "https://openresty.org/package/pubkey.gpg" | sudo -E apt-key add -
          echo "deb https://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
          # add support for HEIC/AVIF images
          sudo apt-add-repository -y "ppa:strukturag/libheif"
          sudo apt-add-repository -y "ppa:strukturag/libde265"
          # add support for saving GIF images
          sudo apt-add-repository -y "ppa:lovell/cgif"
          # install dependencies
          sudo apt-get update
          sudo -E apt-get install -y \
            libcgif-dev libexif-dev libexpat1-dev \
            libfftw3-dev libgsf-1-dev libheif-dev \
            libimagequant-dev liblcms2-dev libmagickwand-dev \
            liborc-0.4-dev libpango1.0-dev libpng-dev \
            libpoppler-glib-dev librsvg2-dev libtiff5-dev \
            libwebp-dev \
            gtk-doc-tools gobject-introspection \
            libtest-nginx-perl \
            lcov
      - name: Install libvips
        if: steps.cache-libvips.outputs.cache-hit != 'true'
        env:
          VIPS_VERSION: ${{ matrix.libvips-version }}
          VIPS_PRE_VERSION: ${{ matrix.libvips-pre-version }}
        run: .ci/install-vips.sh --disable-deprecated
      - name: Prepare environment
        run: |
          echo "$HOME/vips/bin" >> $GITHUB_PATH
          echo "$HOME/nginx/sbin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$HOME/vips/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig" >> $GITHUB_ENV
          mkdir -p build
      - name: Build
        working-directory: build
        run: |
          cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCUSTOM_NGX_FLAGS="--prefix=$HOME/nginx" \
            -DENABLE_COVERAGE=$([ "${{ matrix.coverage }}" = true ] && echo "ON" || echo "OFF") \
            -DBUILD_TESTS=ON
          cmake --build . -- -j$(nproc)
      - name: Run unit tests
        env:
          VIPS_WARNING: 0
        working-directory: build
        run: ctest -j $(nproc) --output-on-failure
      - name: Run integration tests
        env:
          TEST_NGINX_SERVROOT: ${{ github.workspace }}/servroot
        run: prove -r test/nginx
      - name: Generate coverage report
        if: matrix.coverage
        working-directory: build
        run: cmake --build . --target coverage
      - name: Upload coverage to Codecov
        if: matrix.coverage
        uses: codecov/codecov-action@v2
        with:
          file: build/coverage.info
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-imageServer
          location: 'west us'
